import 'product.dart';

class MyProduct{
  static List<Product> allProduct=[
    Product(
      id: 1,
      name: "Service",
      image: "images/Sneakers/S1.jpg",
      price: 100,
      category: "Trending Now",
      description: "This is the most beutiful Shoes ever",
      quantity: 1,
    ),
    Product(
      id: 2,
      name: "Adiddas",
      image: "images/Sneakers/S2.jpg",
      price: 120,
      category: "Out of Stock",
      description: "This is the most beutiful Shoes ever",
      quantity: 1,
    ),
    Product(
      id: 3,
      name: "Skechers",
      image: "images/Sneakers/S3.jpg",
      price: 130,
      category: "New Arrival",
      description: "This is the most beutiful Shoes ever",
      quantity: 1,
    ),
    Product(
      id: 4,
      name: "Nike Orignals",
      image: "images/Sneakers/S4.jpg",
      price: 140,
      category: "Out of stock",
      description: "This is the most beutiful Shoes ever",
      quantity: 1,
    ),
    Product(
      id: 5,
      name: "Bata",
      image: "images/Sneakers/S5.jpg",
      price: 150,
      category: "Top rated",
      description: "This is the most beutiful Shoes ever",
      quantity: 1,
    ),
    Product(
      id: 6,
      name: "Elo",
      image: "images/Jackets/J1.jpg",
      price: 100,
      category: "Trending Now",
      description: "This is the most beutiful Shoes ever",
      quantity: 1,
    ),
    Product(
      id: 7,
      name: "Daraz",
      image: "images/Jackets/J2.jpg",
      price: 120,
      category: "Out of Stock",
      description: "This is the most beutiful Shoes ever",
      quantity: 1,
    ),
    Product(
      id: 8,
      name: "Rad",
      image: "images/Jackets/J3.jpg",
      price: 130,
      category: "New Arrival",
      description: "This is the most beutiful Shoes ever",
      quantity: 1,
    ),
    Product(
      id: 9,
      name: "CutPrice",
      image: "images/Jackets/J4.jpg",
      price: 140,
      category: "Out of stock",
      description: "This is the most beutiful Shoes ever",
      quantity: 1,
    ),
    Product(
      id: 10,
      name: "Denim",
      image: "images/Jackets/J5.jpg",
      price: 150,
      category: "Top rated",
      description: "This is the most beutiful Shoes ever",
      quantity: 1,
    ),
  ];
  static List<Product> jacketList=[
    Product(
      id: 1,
      name: "Elo",
      image: "images/Jackets/J1.jpg",
      price: 100,
      category: "Trending Now",
      description: "This is the most beutiful Shoes ever",
      quantity: 1,
    ),
    Product(
      id: 2,
      name: "Daraz",
      image: "images/Jackets/J2.jpg",
      price: 120,
      category: "Out of Stock",
      description: "This is the most beutiful Shoes ever",
      quantity: 1,
    ),
    Product(
      id: 3,
      name: "Rad",
      image: "images/Jackets/J3.jpg",
      price: 130,
      category: "New Arrival",
      description: "This is the most beutiful Shoes ever",
      quantity: 1,
    ),
    Product(
      id: 4,
      name: "CutPrice",
      image: "images/Jackets/J4.jpg",
      price: 140,
      category: "Out of stock",
      description: "This is the most beutiful Shoes ever",
      quantity: 1,
    ),
    Product(
      id: 5,
      name: "Denim",
      image: "images/Jackets/J5.jpg",
      price: 150,
      category: "Top rated",
      description: "This is the most beutiful Shoes ever",
      quantity: 1,
    ),
  ];
  static List<Product> sneakerList=[
    Product(
      id: 1,
      name: "Service",
      image: "images/Sneakers/S1.jpg",
      price: 100,
      category: "Trending Now",
      description: "This is the most beutiful Shoes ever",
      quantity: 1,
    ),
    Product(
      id: 2,
      name: "Adiddas",
      image: "images/Sneakers/S2.jpg",
      price: 120,
      category: "Out of Stock",
      description: "This is the most beutiful Shoes ever",
      quantity: 1,
    ),
    Product(
      id: 3,
      name: "Skechers",
      image: "images/Sneakers/S3.jpg",
      price: 130,
      category: "New Arrival",
      description: "This is the most beutiful Shoes ever",
      quantity: 1,
    ),
    Product(
      id: 4,
      name: "Nike Orignals",
      image: "images/Sneakers/S4.jpg",
      price: 140,
      category: "Out of stock",
      description: "This is the most beutiful Shoes ever",
      quantity: 1,
    ),
    Product(
      id: 5,
      name: "Bata",
      image: "images/Sneakers/S5.jpg",
      price: 150,
      category: "Top rated",
      description: "This is the most beutiful Shoes ever",
      quantity: 1,
    ),
  ];

}